import struct

f=open('ncnu16.bmp','rb')
fp=f.read()
f.close()
FormatSignature=fp[0:2].decode()
Filesize=struct.unpack('i',fp[2:6])[0]
ImageDataOffset=struct.unpack('i',fp[10:14])[0]
BitmapHeaderSize=struct.unpack('i',fp[14:18])[0]
Width=struct.unpack('i',fp[18:22])[0]
Height=struct.unpack('i',fp[22:26])[0]
NumPlanes=struct.unpack('h',fp[26:28])[0]
BitDepth=struct.unpack('h',fp[28:30])[0]
CompressionType=struct.unpack('i',fp[30:34])[0]
BitmapSize=struct.unpack('i',fp[34:38])[0]
HorzResolution=struct.unpack('i',fp[38:42])[0]
VertResolution=struct.unpack('i',fp[42:46])[0]
NumColorsUsed=struct.unpack('i',fp[46:50])[0]
NumImportantColors=struct.unpack('i',fp[50:54])[0]
print('Format:','\'bmp\'')
print('FormatSignature:','\'%s\''%(FormatSignature))
print('Filesize:',Filesize)
print('ImageDataOffset:',ImageDataOffset)
print('BitmapHeaderSize:',BitmapHeaderSize)
print('Width:',Width)
print('Height:',Height)
print('NumPlanes:',NumPlanes)
print('BitDepth:',BitDepth)
print('CompressionType:',CompressionType)
print('BitmapSize:',BitmapSize)
print('HorzResolution:',HorzResolution)
print('VertResolution:',VertResolution)
print('NumColorsUsed:',NumColorsUsed)
print('NumImportantColors:',NumImportantColors)